### ISSUE TITLE
Fix readthedocs autodoc build

### ISSUE THREAD

**Issue by deepchatterjeeligo** [ML4GW/amplfi#158]
Read the docs build installs only the project docs dependencies: see [latest build](https://readthedocs.org/projects/amplfi/builds/25946097/).

This leads to certain sections of the docs, like API reference not rendered correctly. For example,

- Locally
![image](https://github.com/user-attachments/assets/d92e6a89-0c9a-4744-a6d3-15184d17d89c)

- On RTD
![image](https://github.com/user-attachments/assets/82908629-17f4-459c-a083-d6af333b6363)

The docs build needs to be fixed to render on RTD.

**Comment by EthanMarx** [comment]
Yeah I only installed the `docs` group. You can alter that here: https://github.com/ML4GW/amplfi/blob/main/.readthedocs.yaml#L22

**Comment by EthanMarx** [comment]
Yeah I think if you remove the `--only docs` flag things should work

**Comment by deepchatterjeeligo** [comment]
> Yeah I think if you remove the `--only docs` flag things should work

Let me add `--all-extras` for the readthedocs stage. I'll create a PR.
