### ISSUE TITLE
Paper project

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/amplfi#92]
Create a paper project in the projects directory for all plots related to the paper.

**Comment by deepchatterjeeligo** [comment]
Let's structure this project as having following folder
- scripts
- figures
- notebooks

`scripts` directory has a script per figure which gets stored and versioned in the `figures` folder. And instructive code snippets and visuals can go inside the notebooks.

**Comment by deepchatterjeeligo** [comment]
All figures will be generated with a matplotlib style file. Put a `publication.mplstyle` under the matplotlib configuration directory with the following content:

```
$ cat ${HOME}/.config/matplotlib/publication.mplstyle
font.family : serif
font.serif : Times, Palatino, New Century Schoolbook, Bookman, Computer Modern Roman
font.sans-serif : Helvetica, Avant Garde, Computer Modern Sans serif
font.cursive : Zapf Chancery
font.monospace : Courier, Computer Modern Typewriter
text.usetex : true
figure.figsize : 7.4, 5.8 
axes.titlesize : 18
axes.labelsize : 18
lines.linewidth : 1
lines.markersize : 3
xtick.labelsize : 14
ytick.labelsize : 14
```

Then every figure script should use that:
```python
import matplotlib.pyplot as plt
plt.style.use('publication')
.
.
.
```

**Comment by deepchatterjeeligo** [comment]
the methods paper is submitted. closing.
